FORMAT: 1A

# VUTTR

This is a web api made for BossaBox's challenge

## Authentication
VUTTR API uses passport jwt strategy, so some routes may need Authorization Headers with a valid token.

## Media Types
Requests with a message-body are using plain JSON to set or update resource states.

## Error States
Some of the common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

# Group Auth

## Sign up [/signup]

### Sign up an user [POST]
Will create a new user to the database.

+ Request (application/json)
    + Attributes
        + name: Leo (string, required)
        + lastName: Motta (string, required)
        + email: test@test.com (string, required)
        + password: 123456 (string, required)
        
+ Response 201 (application/json)
    + Attributes
        + message: User created. (string)

## Sign in Collection [/signin]

### Sign in an user [POST]
Will authenticate a with a valid token.

+ Request (application/json)
    + Attributes
        + email: test@test.com (string, required)
        + password: 123456 (string, required)

+ Response 200 (application/json)
    + Attributes
        + userId: 5ce718e91f92721d59bf12c0 (string)
        + token: eyJhbGciOiJIUzI1NiIsInR5c (string)

# Group Tools

## Tools [/tools]

### Get tools [GET]
Will get all the tools.

+ Response 200 (application/json)
    + Attributes (array[Tool])

### Post tool [POST]
Will create a new tool.

+ Request
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    + Attributes (Tool POST)

+ Response 201 (application/json)
    + Attributes (Tool)

## Tools [/tools{?tag}]

### Get tools by tags [GET]
Will get all tools by tag.

+ Parameters
    + tag: node (string, required) - The tag name
+ Response 200 (application/json)
    + Attributes (array[Tool])

## Tool ID Required [/tools/{id}]
+ Parameters
    + id: 5cec64a057f604001f5566c4 (required, string) - ID of a tool as string

### Patch tool [PATCH]
Will modify one or more fields of a tool.

+ Request (application/json)
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    + Attributes (Tool PATCH)

+ Response 200 (application/json)
    + Attributes
        + message: Tool updated! (string)

### Delete tool [DELETE]
Will delete a tool.

+ Request
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
+ Response 200

## Data Structures

### Tool
+ _id: 5ce718e91f92721d59bf12c0 (string, required)
+ title: express (string, required)
+ link: express.com (string, required)
+ description: tool description (string, required)
+ tags (array[Tags], required)

### Tool POST
+ title: express (string, required)
+ link: express.com (string, required)
+ description: tool description (string, required)
+ tags (array[Tags], required)

### Tool PATCH
+ title: express (string)
+ link: express.com (string)
+ description: tool description (string)
+ tags (array[Tags])

### Tags
+ tags: Node, Framework (required)